variables:
  GIT_SUBMODULE_STRATEGY: recursive

peary:
  tags:
    - docker
  image: ubuntu:latest
  before_script:
    - apt-get update -qq && apt-get install -y -qq cmake build-essential libi2c-dev libreadline-dev
  script:
    - mkdir build
    - cd build
    - cmake -DBUILD_example=ON ..
    - make

peary-mac:
  tags:
    - mac
  before_script:
    - source .peary-ci/init_86_64.sh
    - brew install readline && brew link --force readline
  script:
    - mkdir build
    - cd build
    - cmake -DBUILD_example=ON -DINTERFACE_I2C=OFF -DINTERFACE_SPI=OFF -DINTERFACE_SPI_CLICpix2=OFF ..
    - make

# peary-zync:
#  tags:
#    - zynq
#  script:
#    - mkdir build
#    - cd build
#    - cmake -DBUILD_example=ON ..
#    - make